;; YaTeX
(require 'yatex)
(autoload 'yatex-mode "yatex" "Yet Another LaTeX mode" t)
(setq auto-mode-alist
      (append '(("\\.tex$" . yatex-mode)
                ("\\.ltx$" . yatex-mode)
                ("\\.cls$" . yatex-mode)
                ("\\.sty$" . yatex-mode)
                ("\\.clo$" . yatex-mode)
                ("\\.bbl$" . yatex-mode)) auto-mode-alist))
(setq YaTeX-kanji-code nil)
(setq YaTeX-use-LaTeX2e t)
(setq YaTeX-use-AMS-LaTeX t)
(setq tex-command "platex")
(setq dvi2-command "xdvi")
(setq bibtex-command "pbibtex")
(setq dviprint-command-format "dvipdfmx")
;; 自動で改行しない
(add-hook 'yatex-mode-hook '(lambda () (auto-fill-mode -1)))
(add-hook 'yatex-mode-hook '(lambda () (setq mode-name "ytex")))
(add-hook 'yatex-mode-hook '(lambda () (setq-local compile-command "textopdf ")))

;; pdf
(require 'pdf-tools)
(require 'autorevert)
(require 'migemo)
(add-to-list 'auto-mode-alist '("\\.pdf$" . pdf-view-mode))
(setq auto-revert-interval 1)
(add-hook 'pdf-view-mode-hook 'auto-revert-mode)
(add-hook 'pdf-view-mode-hook 'pdf-isearch-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-sync-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-misc-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-annot-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-cache-prefetch-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-isearch-active-mode)
(add-hook 'pdf-view-mode-hook 'pdf-history-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-misc-context-menu-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-occur-dired-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-occur-ibuffer-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-isearch-batch-mode)
(add-hook 'pdf-view-mode-hook 'pdf-links-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-misc-menu-bar-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-misc-size-indication-minor-mode 	)
(add-hook 'pdf-view-mode-hook 'pdf-occur-global-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-outline-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-view-auto-slice-minor-mode)
(add-hook 'pdf-view-mode-hook 'pdf-view-printer-minor-mode)
(pdf-tools-enable-minor-modes 1)
;; pdf-view-dark-minor-mode
;; pdf-view-midnight-minor-mode

